import React, {useEffect,useRef,useState} from 'react';
import {ArrowUp, ArrowUpRight, Check, ChevronDown, Code2, Cpu, GitBranch, Layers, LockKeyhole, MessageSquare, Plus, Settings2, ShieldCheck, Sparkles, Timer, Wallet, X, CircleAlert, Database, ScanLine, SlidersHorizontal, Copy, Square} from 'lucide-react';
import Markdown from 'react-markdown';
import defaults from './defaults.json';
import ThinkingTrace from './components/ThinkingTrace';
import Architecture from './components/Architecture';
import './foundation.css';
import './style.css';

const initial=()=>({...structuredClone(defaults),messages:undefined,user_id:'demo-user',policy:{...defaults.policy,data_residency:null},memory:{...defaults.memory,read:false,write:'off'}});
const names={minicpm:'MiniCPM5 2B',local:'Qwen3 VL',openai:'OpenAI',gemini:'Gemini',google:'Google',anthropic:'Anthropic'};
const groups=[
 ['policy','Privacy & policy',ShieldCheck,[['privacy','Privacy','select',['public','internal','confidential','restricted']],['data_residency','Residency','select',['','US','EU']],['providers','Allowed providers','multi',['openai','anthropic','google','local']],['risk_tier','Risk tier','select',['standard','high']],['on_policy_violation','On violation','select',['reject']]]],
 ['budget','Budget',Wallet,[['max_total_cost_usd','Cost ceiling ($)','number',0,0.01],['max_model_calls','Model calls','number',1,1,20],['max_latency_ms','Latency target (ms)','number',1,1,300000],['max_wall_time_ms','Wall time (ms)','number',1,1,300000],['max_reasoning_tokens','Output / reasoning tokens','number',1,1,100000],['on_exceeded','When exceeded','select',['best_effort','reject']]]],
 ['compute','Compute',Cpu,[['strategy','Strategy','select',['adaptive','fixed']],['initial_tier','Start with','select',['cheap','standard','frontier']],['max_tier','Maximum tier','select',['cheap','standard','frontier']],['reasoning_effort','Reasoning effort','select',['adaptive','low','medium','high']],['escalate_on','Escalate on','multi',['complexity','low_confidence','verification_failure']],['on_escalation_failure','If escalation fails','select',['best_available','reject']]]],
 ['verification','Verification',ScanLine,[['mode','Mode','select',['adaptive','always','off']],['triggers','Check when','multi',['low_confidence','high_risk_domain','factual_claims','code_generation']],['strategies','Strategies','multi',['independent_model','tool_check','schema_validation','consensus']],['failure_action','If checks fail','select',['return_with_uncertainty','reject']]]],
 ['consensus','Consensus',GitBranch,[['trigger.confidence_below','Confidence threshold','number',0,0.01,1],['min_independent_families','Independent families','number',2,1,10],['diversity.vendors','Different vendors','boolean'],['diversity.model_families','Different model families','boolean'],['aggregation_strategy','Aggregation','select',['@majority']],['disagreement','On disagreement','select',['return_with_uncertainty','reject']]]],
 ['memory','Memory',Database,[['read','Read user memory','boolean'],['write','Write memory','select',['off','auto']],['retention','Retention','select',['persistent','request']],['scope','Scope','select',['user']],['conflict_strategy','Conflicting context','select',['prefer_recent']]]],
 ['routing','Routing',Layers,[['strategy','Strategy','select',['adaptive','fixed']],['optimize','Optimize for','multi',['quality','cost','latency']],['optimization_mode','Balance','select',['balanced']],['fallback','Fallback','select',['next_best','none']],['provider_selection','Provider selection','select',['policy_allowed']]]],
 ['response','Response',MessageSquare,[['uncertainty','Show uncertainty','select',['when_material','always']],['citations','Citations','select',['auto','off']],['format','Format','select',['auto','text','json']]]]
];
const pretty=s=>s==='openai'?'OpenAI':s==='@majority'?'Majority':s?s.replaceAll('_',' ').replace(/^./,v=>v.toUpperCase()):'No restriction';
const get=(o,path)=>path.split('.').reduce((v,k)=>v?.[k],o);
function setPath(o,path,value){const next=structuredClone(o),parts=path.split('.');let ptr=next;parts.slice(0,-1).forEach(k=>ptr=ptr[k]);ptr[parts.at(-1)]=value;return next;}
function Field({group,spec,config,setConfig}){
 const [key,label,type,values,step,max]=spec,path=`${group}.${key}`,value=get(config,path);
 const update=v=>setConfig(c=>setPath(c,path,v));
 return <div className={'field '+(type==='boolean'?'boolean':'')}><label htmlFor={path}>{label}</label>
 {type==='select'?<select id={path} value={value??''} onChange={e=>update(e.target.value||null)}>{values.map(v=><option key={v} value={v}>{pretty(v)}</option>)}</select>:
 type==='number'?<input id={path} type="number" min={values} step={step} max={max} required value={value} onChange={e=>update(e.target.value===''?'':Number(e.target.value))}/>:
 type==='boolean'?<input id={path} className="switch" type="checkbox" checked={value} onChange={e=>update(e.target.checked)}/>:
 <div className="check-group" role="group" aria-label={label}>{values.map(v=><label className="check-chip" key={v}><input type="checkbox" checked={value?.includes(v)} onChange={e=>update(e.target.checked?[...value,v]:value.filter(x=>x!==v))}/><span>{pretty(v)}</span></label>)}</div>}
 </div>
}
const stageTitle={memory_read:'Context & memory',classify:'Classify request',privacy_policy:'Apply privacy policy',compute_allocation:'Allocate compute',model_selection:'Eligible models (ranked)',execute:'Generate answer',evaluate:'Evaluate answer',evaluation_result:'Evaluation result',verification_decision:'Verification decision',verify_independent:'Independent review',tool_check:'Tool check',verify_schema:'Validate schema',escalation_decision:'Escalation decision',escalate:'Stronger model',consensus_vote:'Independent answer',consensus:'Consensus',consensus_result:'Majority result',fallback:'Choose fallback',provider_failure:'Provider unavailable',limitation:'Limitation',budget_exceeded:'Budget limit',memory_write:'Save memory',citations:'Sources',return:'Return answer'};
function describe(e){
 if(e.reason)return e.reason;
 if(e.stage==='memory_read')return e.messages?`${e.messages} remembered messages`:'Using this conversation';
 if(e.stage==='privacy_policy')return `${pretty(e.effective_privacy)} data`;
 if(e.stage==='compute_allocation')return `${['Cheap','Standard','Frontier'][e.target_tier]} tier · ${e.remaining_calls} calls left`;
 if(e.stage==='model_selection')return (e.eligible||[]).map(v=>names[v]||v).join(' → ')||'No eligible models';
 if(e.model)return `${names[e.provider]||e.provider}${e.max_output_tokens?' · '+e.max_output_tokens+' token allowance':' · '+(e.finish_reason==='stop'?'complete':e.finish_reason||'complete')}`;
 if(e.confidence!==undefined)return `${Math.round(e.confidence*100)}% score · ${e.passed?'passed':'needs review'}`;
 if(e.stage==='verification_decision')return e.required?e.triggers.map(pretty).join(' · '):'No additional checks needed';
 if(e.passed!==undefined)return e.passed?'Passed':'Needs review';
 if(e.families)return `${e.families.length} / ${e.required} families`;
 if(e.candidates)return e.candidates.map(p=>names[p]).join(' · ')||'No stronger model available';
 return pretty(e.status||e.tool||'Complete');
}
export default function App(){
 const [page,setPage]=useState(()=>location.hash);
 const infoPage=page==='#/how-it-works', architecturePage=page==='#/architecture', contentPage=infoPage||architecturePage;
 useEffect(()=>{const sync=()=>setPage(location.hash);window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);

 const [config,setConfig]=useState(initial),[turns,setTurns]=useState([]),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[health,setHealth]=useState(null),[models,setModels]=useState([]),[selected,setSelected]=useState(null),[editor,setEditor]=useState(null),[editError,setEditError]=useState(''),[elapsed,setElapsed]=useState(0),[copyState,setCopyState]=useState(false),[traceOpen,setTraceOpen]=useState(false);
 const controller=useRef(null),bottom=useRef(null),form=useRef(null),textarea=useRef(null),start=useRef(0);
 const locked=turns.length>0, active=turns.find(t=>t.id===selected)||turns.at(-1);
 const answerModel=active?.result||active?.events.findLast(e=>['execute','escalate'].includes(e.stage));
 useEffect(()=>{let live=true;const check=()=>Promise.all([fetch('/api/health').then(r=>{if(!r.ok)throw Error();return r.json()}),fetch('/api/models').then(r=>r.json())]).then(([,m])=>{if(live){setHealth(true);setModels(m)}}).catch(()=>{if(live)setHealth(false)});check();const timer=setInterval(check,15000);return()=>{live=false;clearInterval(timer);controller.current?.abort()}},[]);
 useEffect(()=>{if(!busy)return;const timer=setInterval(()=>setElapsed((performance.now()-start.current)/1000),100);return()=>clearInterval(timer)},[busy]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth',block:'end'})},[turns.length,busy]);
 const patch=(id,change)=>setTurns(ts=>ts.map(t=>t.id===id?{...t,...(typeof change==='function'?change(t):change)}:t));
 async function send(e){e.preventDefault();if(busy||!draft.trim())return; const invalid=form.current.querySelector(':invalid'); if(invalid){const section=invalid.closest('details');if(section)section.open=true;form.current.reportValidity();return;}
  const text=draft.trim(),id=crypto.randomUUID();const history=turns.filter(t=>t.result).flatMap(t=>[{role:'user',content:t.prompt},{role:'assistant',content:t.result.content}]);
  const payload={...structuredClone(config),messages:[...history,{role:'user',content:text}]};
  if(!payload.memory.read&&payload.memory.write==='off')delete payload.user_id;
  setTurns(ts=>[...ts,{id,prompt:text,events:[],payload,running:true}]);setSelected(id);setDraft('');setBusy(true);start.current=performance.now();setElapsed(0);const abort=new AbortController();controller.current=abort;
  let terminal=false;
  const receive=line=>{if(!line.trim())return;const item=JSON.parse(line);if(item.type==='trace')patch(id,t=>({events:[...t.events,item.event]}));if(item.type==='result'){terminal=true;patch(id,{result:item.data,running:false})}if(item.type==='error'){terminal=true;const detail=typeof item.detail==='string'?item.detail:item.detail?.message||JSON.stringify(item.detail);patch(id,{error:detail,running:false})}};
  try{const r=await fetch('/api/chat/stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:abort.signal});
   if(!r.ok){const data=await r.json();throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail))}
   const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop();lines.forEach(receive)}buffer+=decoder.decode();if(buffer.trim())receive(buffer);if(!terminal)throw Error('The connection ended before a result arrived.');
  }catch(err){patch(id,{error:err.name==='AbortError'?'Run stopped. Any model call already sent may still finish upstream.':err.message,running:false})}finally{setBusy(false);controller.current=null;textarea.current?.focus()}
 }
 function reset(){controller.current?.abort();setTurns([]);setSelected(null);setDraft('');setElapsed(0)}
 const openEditor=()=>{setEditError('');setEditor(JSON.stringify({...config,messages:undefined},null,2))};
 function applyEditor(){try{const value=JSON.parse(editor);if(typeof value!=='object'||!value||Array.isArray(value))throw Error('Use a JSON object.');for(const [g] of groups){if(!value[g]||typeof value[g]!=='object')throw Error(`Missing ${g} settings.`)}if(!value.model)throw Error('Add model, such as @auto.');for(const [g,,,fields] of groups)for(const [k,,type] of fields){const v=get(value,`${g}.${k}`);if(type==='multi'&&!Array.isArray(v))throw Error(`${g}.${k} must be a list.`)}delete value.messages;setConfig(value);setEditor(null)}catch(err){setEditError(err.message)}}
 async function copyRequest(){try{await navigator.clipboard.writeText(JSON.stringify(active?.payload||{...config,messages:[{role:'user',content:draft||'Say hello.'}]},null,2));setCopyState(true);setTimeout(()=>setCopyState(false),1500)}catch{setEditError('Clipboard unavailable. Use the request JSON editor.');openEditor()}}
 return <div className="app-shell">
 <header className="topbar"><div className="brand"><div className="brand-mark"><i/><i/><i/><i/></div><strong>corner crew</strong><span className="slash">/</span><span>{infoPage?'How It Works':architecturePage?'Architecture':'Chat lab'}</span></div><div className="header-right"><nav className="page-nav" aria-label="Main navigation"><a href="#/chat" aria-current={!contentPage?'page':undefined}>Chat</a><a href="#/how-it-works" aria-current={infoPage?'page':undefined}>How It Works</a><a href="#/architecture" aria-current={architecturePage?'page':undefined}>Architecture</a></nav><button style={contentPage?{display:"none"}:undefined} className="quiet trace-open" onClick={()=>setTraceOpen(!traceOpen)}><GitBranch size={14}/>Run trace</button><span className={'connection '+(health?'online':'')}><i/>{health===null?'Connecting':health?'Local API connected':'API unavailable'}</span><button style={contentPage?{display:"none"}:undefined} className="quiet" onClick={reset} disabled={busy}><Plus size={14}/>New conversation</button></div></header>
 {architecturePage&&<Architecture/>}
 {infoPage&&<main className="how-it-works"><div className="infographic-note"><span className="tiny-tag">EXPLAINER</span><span>An illustrated example of the pipeline. Sample metrics and decisions—not a live run.</span><a href="#/chat">Back to chat <ArrowUpRight size={13}/></a></div><iframe src="/infographic/index.html" title="How It Works: interactive pipeline infographic" sandbox="allow-scripts"/></main>}
 <div className="workspace" style={contentPage?{display:'none'}:undefined}><aside className="settings-panel"><div className="panel-heading"><div><span className="eyebrow">01 / CONFIGURE</span><h2>Request settings</h2></div><Settings2 size={17}/></div><p className="muted intro">Set the rules. Then start a conversation.</p>
 <form ref={form} className="settings-form" onSubmit={e=>e.preventDefault()}><fieldset disabled={locked||busy}>
 <div className="model-select field"><label htmlFor="model-choice">Model selection <span className="tiny-tag">{config.provider?'PINNED':'AUTO'}</span></label><select id="model-choice" value={config.provider||'@auto'} onChange={e=>setConfig(c=>({...c,model:'@auto',provider:e.target.value==='@auto'?undefined:e.target.value}))}><option value="@auto">Adaptive · choose for me</option>{models.map(m=><option key={m.provider} value={m.provider}>{names[m.provider]||m.model}</option>)}</select></div>
 {groups.map(([group,label,Icon,fields],index)=><details className="setting-section" key={group} open={index===0?true:undefined}><summary><Icon size={15}/><span>{label}</span><small>{group==='policy'?pretty(config.policy.privacy):group==='budget'?`${config.budget.max_model_calls} calls`:group==='memory'?config.memory.read||config.memory.write==='auto'?'On':'Off':group==='consensus'?`${config.consensus.min_independent_families} families`:group==='response'?pretty(config.response.format):pretty(config[group].mode||config[group].strategy||'')}</small><ChevronDown size={13}/></summary><div className="section-body">{fields.map(spec=><Field key={spec[0]} group={group} spec={spec} config={config} setConfig={setConfig}/>)}{group==='memory'&&<div className="field"><label htmlFor="user_id">User ID</label><input id="user_id" required={config.memory.read||config.memory.write==='auto'} value={config.user_id||''} onChange={e=>setConfig(c=>({...c,user_id:e.target.value}))}/></div>}{group==='response'&&config.response.format==='json'&&<p className="hint">Add an optional JSON Schema in the payload editor.</p>}{group==='policy'&&config.policy.data_residency&&<p className="hint">Requires matching server residency metadata.</p>}</div></details>)}
 </fieldset></form><div className="settings-bottom">{locked&&<p className="lock-note"><LockKeyhole size={12}/>Settings locked for this conversation.</p>}<button className="quiet payload-button" onClick={openEditor}><Code2 size={14}/>{locked?'View configuration':'Edit full payload'}<ArrowUpRight size={13}/></button></div></aside>
 <main className="conversation"><div className="conversation-heading"><div className="eyebrow">02 / CONVERSATION</div><span className="session-pill"><span/>Single session</span></div>
 <div className="messages">{turns.length===0?<div className="empty-state"><div className="hero-glyph"><GitBranch size={26}/></div><h1>A little more than<br/>a model call.</h1><p>One conversation. Your rules.<br/>Watch every decision along the way.</p><div className="suggestions">{['Say hello in one sentence.','Write a Python function to reverse a string.','Explain the trade-offs of a local AI model.'].map((s,i)=><button key={s} onClick={()=>{setDraft(s);textarea.current?.focus()}}><span>{[<MessageSquare size={15}/>,<Code2 size={15}/>,<Layers size={15}/>][i]}{['Start simple','Check some code','Try a harder question'][i]}</span><ArrowUpRight size={13}/></button>)}</div></div>:turns.map((t,index)=><section key={t.id} className="turn"><div className="user-message"><span className="message-label">YOU</span><p>{t.prompt}</p></div><div className="assistant-message"><div className="assistant-label"><div className="mini-mark"><Sparkles size={14}/></div><strong>Corner Crew</strong><button className={'run-link '+(active?.id===t.id?'selected':'')} onClick={()=>setSelected(t.id)}>Run {String(index+1).padStart(2,'0')}<ArrowUpRight size={12}/></button></div><ThinkingTrace events={t.events} running={t.running} failed={!!t.error}/>{t.running&&<div className="working"><span className="pixel-loader"><i/><i/><i/><i/><i/><i/><i/><i/><i/></span><span>Processing</span><code>{elapsed.toFixed(1)}s</code></div>}{t.error&&<div className="notice error" role="alert"><CircleAlert size={16}/><div><strong>Request stopped</strong><p>{t.error}</p></div></div>}{t.result&&<><div className="answer"><Markdown>{t.result.content}</Markdown></div>{t.result.uncertainty.length>0&&<details className="notice"><summary><CircleAlert size={14}/>Needs review · {t.result.uncertainty.length} note{t.result.uncertainty.length>1?'s':''}<ChevronDown size={13}/></summary><ul>{t.result.uncertainty.map(w=><li key={w}>{w}</li>)}</ul></details>}<div className="answer-meta"><span><Cpu size={12}/>{names[t.result.provider]||t.result.model}</span><span>{t.result.usage.model_calls} calls</span><span>{(t.result.usage.elapsed_ms/1000).toFixed(1)}s</span><span>${t.result.usage.estimated_cost_usd.toFixed(4)}</span></div></>}</div></section>)}<div ref={bottom}/></div>
 <div className="composer-wrap"><form className="composer" onSubmit={send}><textarea ref={textarea} aria-label="Message" placeholder="Ask something. Watch the steps." value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send(e)}}} rows={2}/><div className="composer-footer"><span><Sparkles size={14}/>{config.provider?names[config.provider]:'Adaptive routing'}<span className="divider"/> <ShieldCheck size={13}/>{pretty(config.policy.privacy)}</span>{busy?<button type="button" className="send" aria-label="Stop run" onClick={()=>controller.current?.abort()}><Square size={15}/></button>:<button className="send" type="submit" aria-label="Send message" disabled={!draft.trim()||health!==true}><ArrowUp size={18}/></button>}</div></form><p className="composer-note">Enter to send <span>·</span> Shift + Enter for a new line <span>·</span> Local demo</p></div>
 </main>
 <aside className={"run-panel "+(traceOpen?"show-trace":"")}><button className="icon-button trace-close" aria-label="Close run trace" onClick={()=>setTraceOpen(false)}><X size={16}/></button><div className="panel-heading"><div><span className="eyebrow">03 / OBSERVE</span><h2>Behind the answer</h2></div><span className={'live-tag '+(active?.running?'is-live':'')}>{active?.running?'LIVE':active?'TRACE':'READY'}</span></div><p className="muted intro">Actual steps. As they happen.</p>
 {!active?<><div className="flow-preview">{[[ShieldCheck,'Classify & protect','Understand the request'],[Database,'Gather context','Recall relevant memory'],[Cpu,'Allocate & route','Choose the right model'],[Sparkles,'Execute & evaluate','Generate, then assess'],[GitBranch,'Verify or escalate','Check when needed']].map(([Icon,title,desc],i)=><div className="preview-step" key={title}><span className="step-icon"><Icon size={16}/></span><div><strong>{title}</strong><p>{desc}</p></div><code>0{i+1}</code></div>)}</div><div className="ready-card"><span className="green-dot"/><div><strong>{models.filter(m=>m.is_local).length} local models configured</strong><p>MiniCPM for classification.<br/>Qwen available for deeper work.</p></div></div></>:<><div className="run-stats"><div><span>MODEL CALLS</span><strong>{active.result?.usage.model_calls??active.events.filter(e=>e.max_output_tokens).length}<small> / {active.payload.budget.max_model_calls}</small></strong></div><div><span>ELAPSED</span><strong>{active.running?elapsed.toFixed(1):((active.result?.usage.elapsed_ms??active.events.at(-1)?.elapsed_ms??0)/1000).toFixed(1)}<small>s</small></strong></div></div>{answerModel&&<div className="answer-model-card" aria-live="polite"><span className="eyebrow">{active.result?'ANSWERED BY':'SELECTED TO ANSWER'}</span><strong><Cpu size={16}/>{names[answerModel.provider]||answerModel.provider}<span>{['local','minicpm'].includes(answerModel.provider)?'LOCAL':'CLOUD'}</span></strong><code>{answerModel.model}</code></div>}<div className="event-feed">{active.events.map((e,i)=><details key={i} className={'event-row '+((['provider_failure','budget_exceeded','limitation'].includes(e.stage)||e.passed===false)?'warn':'')}><summary><span className="event-dot">{active.running&&i===active.events.length-1?<span className="spinner"/>:<Check size={11}/>}</span><div><strong>{stageTitle[e.stage]||pretty(e.stage)}</strong><p>{describe(e)}</p></div><code>{(e.elapsed_ms/1000).toFixed(1)}s</code></summary><pre>{JSON.stringify(e,null,2)}</pre></details>)}{active.error&&<div className="trace-error"><CircleAlert size={13}/>Stopped before completion</div>}</div>{active.result&&<div className="run-outcome"><span className={active.result.status==='ok'?'green-dot':'amber-dot'}/><strong>{active.result.status==='ok'?'Run complete':'Returned with uncertainty'}</strong>{active.result.confidence!==null&&<small>Evaluator score: {Math.round(active.result.confidence*100)}% · heuristic</small>}</div>}</>}
 <div className="run-bottom"><button className="quiet" onClick={copyRequest}>{copyState?<Check size={13}/>:<Copy size={13}/>} {copyState?'Copied':'Copy request JSON'}</button><a href="https://www.beautifului.dev/" target="_blank" rel="noreferrer">Elements by Beautiful UI<ArrowUpRight size={11}/></a></div></aside></div>
 {editor!==null&&<div className="modal-backdrop" onClick={()=>setEditor(null)}><div className="payload-modal" role="dialog" aria-modal="true" aria-label="Request configuration" onClick={e=>e.stopPropagation()}><header><div><h2>Request configuration</h2><p>All controls sent with each message.</p></div><button className="icon-button" aria-label="Close configuration" onClick={()=>setEditor(null)}><X size={18}/></button></header><textarea aria-label="Configuration JSON" spellCheck="false" value={editor} readOnly={locked} onChange={e=>setEditor(e.target.value)}/>{editError&&<p className="edit-error" role="alert">{editError}</p>}<footer><span>{locked?'Start a new conversation to change settings.':'Messages are added from your conversation.'}</span><button className="primary" onClick={locked?()=>setEditor(null):applyEditor}>{locked?'Done':'Apply configuration'}</button></footer></div></div>}
 </div>
}
