import React from 'react';
import {ArrowUpRight, Laptop, Cloud, Network, GitBranch} from 'lucide-react';

export default function Architecture(){
 return <main className="architecture-page"><div className="architecture-content">
  <header className="architecture-heading"><span className="eyebrow">SYSTEM DESIGN</span><h1>One control plane.<br/>Local first, cloud when needed.</h1><p>How requests, models, and infrastructure fit together—from the local demo to a proposed hybrid deployment.</p></header>
  <section className="architecture-section" aria-labelledby="deployment-heading"><div className="architecture-section-heading"><div><span className="eyebrow">01 / DEPLOYMENT</span><h2 id="deployment-heading">The bigger picture</h2></div><span className="tiny-tag">PROPOSED ARCHITECTURE</span></div>
   <figure className="deployment-figure"><a href="/architecture/deployment.png" target="_blank" rel="noreferrer" aria-label="Open deployment diagram at full size"><img src="/architecture/deployment.png" alt="AI control plane hybrid deployment: client apps call a local FastAPI service with local models. Proposed overflow routes through a Google Cloud load balancer to autoscaled GKE pods connected to external model providers. Memory, storage, logging, monitoring, and an optimization loop support the cloud service."/></a><figcaption><span>Local development → managed cloud deployment → external model providers</span><a href="/architecture/deployment.png" target="_blank" rel="noreferrer">Open full-size diagram <ArrowUpRight size={14}/></a></figcaption></figure>
   <div className="architecture-zones">{[[Laptop,'Local environment','Clients call FastAPI. Local models handle classification and can generate and evaluate answers.'],[Cloud,'Google Cloud','The proposed deployment adds a load balancer, autoscaled GKE services, shared memory, storage, and observability.'],[Network,'Model providers','The control plane selects eligible local or cloud models using policy, budget, and compute settings.']].map(([Icon,title,text])=><article key={title}><Icon size={20}/><h3>{title}</h3><p>{text}</p></article>)}</div>
   <details className="architecture-scope" open><summary>How this maps to the running demo</summary><p>The demo uses <strong>llama.cpp</strong> for MiniCPM and Qwen, plus a configured Gemini connection. Its API endpoints are <code>/chat</code> and <code>/chat/stream</code>, and optional memory is stored in local SQLite.</p><p>The supplied diagram shows the target design: its Ollama label corresponds to our llama.cpp runtime. GKE, Tailscale, automatic 429 overflow, cloud stores, and the Alpha Evolve optimization loop are proposed infrastructure, not deployed demo features. The diagram’s <code>/chat/v1</code> is a proposed endpoint.</p></details>
  </section>
  <section className="architecture-section" aria-labelledby="breakdown-heading"><div className="architecture-section-heading"><div><span className="eyebrow">02 / ARCHITECTURE BREAKDOWN</span><h2 id="breakdown-heading">Why an AI control plane?</h2></div><GitBranch size={19}/></div><p className="architecture-lead">The difference between a single model call and a request managed through policy, execution, and evaluation.</p>
   <div className="architecture-comparison"><article><span className="tiny-tag">SINGLE HOP</span><h3>Simple model routing</h3><div className="architecture-path">Prompt → Pick model → Output</div><ul><li>Selects a model and returns its response.</li><li>Policy enforcement and budget tracking need separate logic.</li><li>Verification and escalation need to be added explicitly.</li><li>Memory and context depend on the surrounding application.</li></ul></article><article><span className="tiny-tag">ADAPTIVE PIPELINE</span><h3>AI control plane</h3><div className="architecture-path">Classify → Apply policy → Route → Execute → Evaluate</div><ul><li>Filters model choices using privacy and residency requirements.</li><li>Allocates compute within cost, time, and call limits.</li><li>Can verify, escalate, or seek consensus when requested and feasible.</li><li>Keeps memory and the execution trace at the application layer.</li></ul></article></div>
   <a className="architecture-next" href="#/how-it-works">Explore the request flow <ArrowUpRight size={15}/></a>
  </section>
 </div></main>
}
